### ISSUE TITLE
docker container setup

### ISSUE THREAD

**Issue by kiniadit** [hackoregon/transportation-system-backend#2]
Issues so far - 

- django not recognizing docker local ports. 
- postgres container needs setup with volume

**Comment by bhgrant8** [comment]
In regards to: 
django not recognizing docker local ports.

this may be a question of your host postgres not allowing outside connections. it is possible to change your config to open up, not sure if this is the most secure option but possible. 
General Guide:

http://winstonkotzan.com/blog/2017/06/01/connecting-to-external-postgres-database-with-docker.html

Alternate is maybe setting up the volume in the docker-compose. that way the persistent storage is in the hd but connection is isolated through container.

adding something along the line of the following to the db section of the compose file:

```
volumes:
  - /path/to/your/host/directory:/var/lib/postgresql/data
```

**Comment by kiniadit** [comment]
docker container setup complete. I can work on documenting this once I discuss this next week.
