### ISSUE TITLE
Investigate the use of a Wait-for-it type script

### ISSUE THREAD

**Issue by bhgrant8** [hackoregon/transportation-system-backend#20]
Reviewing Docker-compose documentation, it appears that using the 'depends_on' key in the compose file will only wait for the container to be on, not weather it has completed setup.

Are there any startup issues that may result from this or health check issues?

Docker seems to recommend a use of a setup script:
https://docs.docker.com/compose/startup-order/

Should we pursue this?
Maybe cause of: https://github.com/hackoregon/transportation-system-backend/issues/18

**Comment by znmeb** [comment]
We definitely need a client to wait for PostgreSQL to be listening ... Let me dig into that

**Comment by znmeb** [comment]
Closing here - I put up a master task list at https://github.com/hackoregon/transportation-systems/issues/19
