### ISSUE TITLE
Change the Docker Image for the Database and update necessary files

### ISSUE THREAD

**Issue by bhgrant8** [hackoregon/transportation-system-backend#25]
We need to update to the new version of our db image. The base files are located in this directory:
https://github.com/hackoregon/data-science-pet-containers as the 'postgis' image

What changes need to be made?

I see:

1. Match the `docker-compose.yml` files 'db' portion to the 'postgis' portion of the `small.yml` file.
2. update the `DOCKERFILE.db` file to match the `DOCKERFILE.postgis` 
3. create a BACKUPS directory and add this file: https://github.com/hackoregon/data-science-pet-containers/blob/master/containers/Backups/restore-all.sh
4. confirm database backup files will be in the .gitignore
5. make sure to download database backups into the folder before running container.

**Comment by znmeb** [comment]
Looks about right - where's the current docker-compose.yml? It'll probably be faster if I do a branch and a pull request.

**Comment by bhgrant8** [comment]
Here is the compose: https://github.com/hackoregon/transportation-system-backend/blob/staging/docker-compose.yml

And dockerfile: https://github.com/hackoregon/transportation-system-backend/blob/staging/DOCKERFILE.db

**Comment by znmeb** [comment]
OK - branch is https://github.com/hackoregon/transportation-system-backend/tree/znmeb-merge-new-database

I have the build working on my workstation - for some reason `docker-compose` didn't see the image name variables so I hard-coded them in `docker-compose.yml`.

`docker run -it --rm -p 5439:5432 db` works and I can see the databases in pgAdmin - I restored both `odot_crash_data` and `passenger_census` (ridership data).

TBD:

1. Test build on a different machine.
2. Figure out the environment thing
3. Make sure it all runs

**Comment by znmeb** [comment]
Fixed in branch znmeb-merge-new-database
