### ISSUE TITLE
Create scalable naming conventions for api files

### ISSUE THREAD

**Issue by bhgrant8** [hackoregon/transportation-system-backend#4]
Looking forward to project season, we may need separate startup and config files for different environments, such as a local development build, a travis build, or production build. We don't need to actually know them now but building a naming convention which allows for nTH environment.

Maybe following an `environment-filetype` approach may be useful?

Some questions with this are how do we need to change existing files to accommodate this structure? Also what changes to cli commands are needed? Anything else this will impact?

**Comment by kiniadit** [comment]
my latest pull request uses`.env` files for environment variables. I support this approach since, as you mentioned, it allows for separation of build, dev environments etc.

**Comment by bhgrant8** [comment]
going to close this out as is addressed in the pr mentioned
