### ISSUE TITLE
Remove PostGIS and drop back to PostgreSQL 9.6 for the database image

### ISSUE THREAD

**Issue by znmeb** [hackoregon/transportation-system-backend#42]
Currently DevOps is planning on deploying PostgreSQL 9.6 on Amazon Linux 2, which does not yet support PostGIS. Since we aren't currently using the GIS queries, we should remove PostGIS from the database image and drop back to PostgreSQL 9.6 so we match what will be deployed.

**Comment by znmeb** [comment]
I'm collecting research on this - here's a few links I've found so far:

* https://gis.stackexchange.com/questions/112057/sql-query-to-have-a-complete-geojson-feature-from-postgis/191446#191446
* http://www.postgresonline.com/journal/archives/267-Creating-GeoJSON-Feature-Collections-with-JSON-and-PostGIS-functions.html
* https://gis.stackexchange.com/questions/142391/storing-geojson-featurecollection-to-postgresql-with-postgis

One approach would be to switch from GeoDjango to regular Django for serving the API and use a straight PostgreSQL 9.6 database, matching the AWS server. We would then need to do any GIS calculations in regular Python. There are a number of libraries for this - I'll post what I've found as soon as I dig up the reference books I have.

**Comment by znmeb** [comment]
Here are the two books I recommend:
* [Geoprocessing with Python](https://www.manning.com/books/geoprocessing-with-python)
* [The PyQGIS Programmer's Guide - Extending QGIS 3 with Python 3](https://locatepress.com/ppg3)

Personally, I think PyQGIS is the way to go because you have maps as standard equipment *and* can connect to GIS-enabled databases.

**Comment by bhgrant8** [comment]
closing, opening ticket to update to examplar
