### ISSUE TITLE
Get Started guide for Developers

### ISSUE THREAD

**Issue by bhgrant8** [hackoregon/transportation-system-backend#5]
Walk new member of dev team through getting environment up and running:

Possible Outline:

minimum requirements (should assume dev can get everything up and running independently)
how to create env.sh
any build process
how to start container
how to contribute (git project flow)

**Comment by kiniadit** [comment]
I can work on this after our meeting tomorrow. Do i just add to readthedocs?

**Comment by bhgrant8** [comment]
This will go into our readthedocs collection but we should have this in the main base readme file

**Comment by znmeb** [comment]
I just pushed the local Docker setup README - https://github.com/hackoregon/data-science-pet-containers/blob/master/README.md

TBD: Integration with a Cookiecutter Data Science project and with the API container. I've got a "Help Wanted" open for the Cookiecutter piece but I'll probably hack on it myself next week. I'll open an issue for API integration.

**Comment by bhgrant8** [comment]
I think we have this pretty well completed
