### ISSUE TITLE
Dare I say it, ... Testing.

### ISSUE THREAD

**Issue by bhgrant8** [hackoregon/transportation-system-backend#8]
Define our expectations around testing of django code and API
What other things to test?
Data validation?

**Comment by bhgrant8** [comment]
So https://github.com/hackoregon/transportation-system-backend/pull/23

allows for tests to be run in the docker container, spinning up a test db, we need to define:

our testing reqs

how to load mock data

start writing tests

**Comment by znmeb** [comment]
Do we need mock data when we have two small real datasets? ;-)

**Comment by bhgrant8** [comment]
related to https://github.com/hackoregon/transportation-system-backend/pull/41

**Comment by bhgrant8** [comment]
testing has been implemente
