### ISSUE TITLE
Version API from beginning

### ISSUE THREAD

**Issue by bhgrant8** [hackoregon/transportation-system-backend#9]
We may have a few iterations of our api where other Hack Oregon teams are using endpoints, public partners may use others, and our frontend teams may use the service a different way. 

To allow iteration and growth, continue to follow a RESTful architecture, but not force deprecation on our users, we should plan for versioning from the beginning. (See #7 in https://hackernoon.com/restful-api-designing-guidelines-the-best-practices-60e1d954e7c9)

URL versioning seems to have advantages over header based, but lets talk about best practice

**Comment by bhgrant8** [comment]
Good article on versioning in Django Rest Framework to consider:
https://gearheart.io/blog/api-versioning-with-django-rest-framework/

**Comment by znmeb** [comment]
The only two APIs I use heavily use URL versioning. I think Twitter does too. But old versions *do* need deprecation and eventual removal, right?

**Comment by BrianHGrant** [comment]
Yes and this process is far easier when stating a version of the api will
be deprecated on a certain date.

**Comment by kiniadit** [comment]
I'm thinking AcceptHeaderVersioning would be the way to go. DRF supports this and looks relatively easy to implement.

Though I'm stuck on figuring out how to incorporate custom content-types with Django (e.g. Accept: application/vnd.company.myapp.customer-v3+json)

[Best Practices for API versioning](https://stackoverflow.com/questions/389169/best-practices-for-api-versioning
)

**Comment by bhgrant8** [comment]
I believe header versioning has been implemented?  Are you still having issues with the custom content-types?

**Comment by bhgrant8** [comment]
implemented in pr #38
